spring.application.name=API-Middleware
server.port=8083
python.auth.base-url=http://localhost:8080
security.jwt.secret=UGEH/mCjBb7XDrFwKh7iF5aneok1OmrKsQfichV11UokC2ptMeSqA98l6g3+PwMHywcH0Xu+yOt2B/SUrLi2cw==
security.jwt.expiration=3600000
spring.cloud.gateway.forwarded.enabled=false
spring.cloud.gateway.x-forwarded.enabled=false
server.forward-headers-strategy=none
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
